ALTER TABLE [dbo].[VendorSourceItems]
    ADD CONSTRAINT [UQ_ProductID_VendorID] UNIQUE NONCLUSTERED ([ProductID] ASC, [VendorID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

